version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/data

  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    # depends_on:
    #   - server-database
    env_file:
      - ./server/variables.env
    # environment:
    #   - DATABASE_URL=server-database     

  # server-database:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./db:/data/db